title: <p align="center"> Larry Chuon </p>
logo: /assets/img/asiq.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/chuon/">LinkedIn</a> |
  <a href="https://agiq.github.io/">GitHub</a>
  
  <br>   
  I've interest in Data Science, Machine Learning, Deep Learning, and Artificial Intelligence. 
  Currently, I'm working on DevOps and DevSecOps.  I hope to transition into MLOps with 2 years.
  <br>
  </p>



theme: jekyll-theme-minimal